/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "factory_data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(edge_device_factory_FactoryData, edge_device_factory_FactoryData, AUTO)





