/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_EDGE_DEVICE_FACTORY_FACTORY_DATA_PB_H_INCLUDED
#define PB_EDGE_DEVICE_FACTORY_FACTORY_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _edge_device_factory_WifiMode {
    edge_device_factory_WifiMode_WIFI_MODE_UNSPECIFIED = 0,
    edge_device_factory_WifiMode_WIFI_MODE_MESH = 1,
    edge_device_factory_WifiMode_WIFI_MODE_STA = 2,
    edge_device_factory_WifiMode_WIFI_MODE_WIFI = 3
} edge_device_factory_WifiMode;

typedef enum _edge_device_factory_CountryCode {
    edge_device_factory_CountryCode_COUNTRY_UNSPECIFIED = 0,
    edge_device_factory_CountryCode_COUNTRY_US = 1,
    edge_device_factory_CountryCode_COUNTRY_CA = 2,
    edge_device_factory_CountryCode_COUNTRY_JP = 3,
    edge_device_factory_CountryCode_COUNTRY_AU = 4,
    edge_device_factory_CountryCode_COUNTRY_NZ = 5,
    edge_device_factory_CountryCode_COUNTRY_EU = 6
} edge_device_factory_CountryCode;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(32) edge_device_factory_FactoryData_device_public_key_t;
typedef PB_BYTES_ARRAY_T(32) edge_device_factory_FactoryData_device_private_key_t;
typedef PB_BYTES_ARRAY_T(64) edge_device_factory_FactoryData_credential_signature_t;
typedef PB_BYTES_ARRAY_T(32) edge_device_factory_FactoryData_signer_public_key_t;
typedef struct _edge_device_factory_FactoryData {
    edge_device_factory_WifiMode mode;
    edge_device_factory_CountryCode country;
    char serial_number[65];
    edge_device_factory_FactoryData_device_public_key_t device_public_key;
    edge_device_factory_FactoryData_device_private_key_t device_private_key;
    edge_device_factory_FactoryData_credential_signature_t credential_signature;
    edge_device_factory_FactoryData_signer_public_key_t signer_public_key;
    char ssid[33];
    char passphrase[65];
    char ble_pin_code[7];
} edge_device_factory_FactoryData;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _edge_device_factory_WifiMode_MIN edge_device_factory_WifiMode_WIFI_MODE_UNSPECIFIED
#define _edge_device_factory_WifiMode_MAX edge_device_factory_WifiMode_WIFI_MODE_WIFI
#define _edge_device_factory_WifiMode_ARRAYSIZE ((edge_device_factory_WifiMode)(edge_device_factory_WifiMode_WIFI_MODE_WIFI+1))

#define _edge_device_factory_CountryCode_MIN edge_device_factory_CountryCode_COUNTRY_UNSPECIFIED
#define _edge_device_factory_CountryCode_MAX edge_device_factory_CountryCode_COUNTRY_EU
#define _edge_device_factory_CountryCode_ARRAYSIZE ((edge_device_factory_CountryCode)(edge_device_factory_CountryCode_COUNTRY_EU+1))


#define edge_device_factory_FactoryData_mode_ENUMTYPE edge_device_factory_WifiMode
#define edge_device_factory_FactoryData_country_ENUMTYPE edge_device_factory_CountryCode


/* Initializer values for message structs */
#define edge_device_factory_FactoryData_init_default {_edge_device_factory_WifiMode_MIN, _edge_device_factory_CountryCode_MIN, "", {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, "", "", ""}
#define edge_device_factory_FactoryData_init_zero {_edge_device_factory_WifiMode_MIN, _edge_device_factory_CountryCode_MIN, "", {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, "", "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define edge_device_factory_FactoryData_mode_tag 1
#define edge_device_factory_FactoryData_country_tag 2
#define edge_device_factory_FactoryData_serial_number_tag 4
#define edge_device_factory_FactoryData_device_public_key_tag 5
#define edge_device_factory_FactoryData_device_private_key_tag 6
#define edge_device_factory_FactoryData_credential_signature_tag 7
#define edge_device_factory_FactoryData_signer_public_key_tag 8
#define edge_device_factory_FactoryData_ssid_tag 9
#define edge_device_factory_FactoryData_passphrase_tag 10
#define edge_device_factory_FactoryData_ble_pin_code_tag 11

/* Struct field encoding specification for nanopb */
#define edge_device_factory_FactoryData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1) \
X(a, STATIC,   SINGULAR, UENUM,    country,           2) \
X(a, STATIC,   SINGULAR, STRING,   serial_number,     4) \
X(a, STATIC,   SINGULAR, BYTES,    device_public_key,   5) \
X(a, STATIC,   SINGULAR, BYTES,    device_private_key,   6) \
X(a, STATIC,   SINGULAR, BYTES,    credential_signature,   7) \
X(a, STATIC,   SINGULAR, BYTES,    signer_public_key,   8) \
X(a, STATIC,   SINGULAR, STRING,   ssid,              9) \
X(a, STATIC,   SINGULAR, STRING,   passphrase,       10) \
X(a, STATIC,   SINGULAR, STRING,   ble_pin_code,     11)
#define edge_device_factory_FactoryData_CALLBACK NULL
#define edge_device_factory_FactoryData_DEFAULT NULL
extern const pb_msgdesc_t edge_device_factory_FactoryData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define edge_device_factory_FactoryData_fields &edge_device_factory_FactoryData_msg

/* Maximum encoded size of messages (where known) */
#define EDGE_DEVICE_FACTORY_FACTORY_DATA_PB_H_MAX_SIZE edge_device_factory_FactoryData_size
#define edge_device_factory_FactoryData_size     346

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
