#ifndef EDGEZ_LOG_STREAM_PROTOCOL_H
#define EDGEZ_LOG_STREAM_PROTOCOL_H

#define EDGEZ_LOG_STREAM_MAGIC_0 'L'
#define EDGEZ_LOG_STREAM_MAGIC_1 'G'
#define EDGEZ_LOG_STREAM_VERSION 2
#define EDGEZ_LOG_STREAM_HEADER_LEN 5
#define EDGEZ_LOG_STREAM_RECORD 1
#define EDGEZ_LOG_STREAM_SET_LEVEL 2
#define EDGEZ_LOG_STREAM_LEVEL_RESPONSE 3
#define EDGEZ_LOG_STREAM_LEVEL_ERROR 0xff

#endif
